### ISSUE TITLE
I/O Task List

### ISSUE THREAD

**Issue by orchetect** [orchetect/MIDIKit#19]
## I/O Task List

Medium-priority tasks.

- [ ] `IO.Manager`: Add remaining accessors for things like CoreMIDI ExternalDevices etc.
- [ ] `IO.Manager.InternalNotification` cases need fleshing out
- [ ] `MIDIIOObjectProtocol`: Add remaining `set...()` property methods (counterparts to `get...()` property methods)
- [ ] Carry MIDI packet timestamp through to `MIDI.Event` consumers? (`ReceivesMIDIEvents` protocol)
  - This may not be needed, `ReceiveHandler`s get timestamp as part of the packet data and can be handled there if desired
- [ ] `Device`/`Entity`/`Endpoint`: cache object images in memory internally after first access:
  MIDIIOObjectProtocol Properties.swift: `var getImageAsUIImage: UIImage?`

## I/O Backburner

Low-priority tasks that need research.

- [ ] Bluetooth/network MIDI support
- [ ] Use `Unmanaged` instead of pointers?
- [ ] MIDI non-persistent thru connections: do they need to be reconnected (refreshed) when a received MIDI notification indicates setup has changed or things were added/removed in the CoreMIDI subsystem? or does CoreMIDI handle some of that autonomously?
- [ ] MIDI non-persistent thru connections: what happens when ports involved disappear and reappear in the system? Do we need to worry about a refreshConnections(in:) method like with the inputs and outputs?
- [ ] `MIDI.IO.getConnectionUniqueID()` can be `Int32` or `CFData` - see docs:
  > "The value provided may be an integer. To indicate that a driver connects to multiple external objects, pass the array of big-endian SInt32 values as a CFData object."
- [ ] Does CoreMIDI `MIDIOutputPortCreate`/`MIDIInputPortCreate` need a meaningful name or is UUID fine?
